  name: ChatWithGroup
  main: server.natural.Main
  version: "1.3.1"
  api-version: 1.17
  author: [Jerry]
  commands:
    smg: # 命令的基本名，请不要使用奇怪的字符！
      aliases: # 别名，方便玩家使用
        - "smg"
        - "sendmessagetogroup"
      usage: "/smg <要发送的信息>" # 用法
      description: "发送信息给群里的人" # 描述
    systeminfo:
      aliases:
        - "si"
        - "load"
      usage: /systeminfo
      description: "获取服务器负载状况"
    botinvite:
      aliases:
        - "botinvite"
        - "inviteplayeringroup"
      usage: /botinvite
      description: "邀请服务器玩家"