  name: ChatWithGroup
  main: server.natural.Main
  version: "${project.version}"
  api-version: 1.17
  author: [Jerry , wangxyper]
  commands:
    smg: # 命令的基本名，请不要使用奇怪的字符！
      aliases: # 别名，方便玩家使用
        - "smg"
        - "sendmessagetogroup"
      usage: "/smg <要发送的信息>" # 用法
      description: "发送信息给群里的人" # 描述
    botinvite:
      aliases:
        - "botinvite"
        - "inviteplayeringroup"
      usage: "/botinvite"
      description: "邀请服务器玩家"
    messageforwarding:
      aliases:
        - "mf"
        - "forwarding"
      usage: "/mf"
      description: "MessageForwarding"
    cwgversion:
      aliases:
        - "cwgver"
        - "chatwithgroupversion"
      usage: "/cwgver"
      permission: "cwg.ver"
      description: "查看ChatWithGroup插件的信息"
    cwg:
      aliases:
        - "cwg"
        - "chatwithgroup"
      usage: "/cwg reload"
      permission: "cwg.reload"
      description: "重置CWG插件的配置文件"