  name: ChatWithGroup
  main: server.natural.chatwithgroup.Main
  version: "${project.version}"
  api-version: 1.17
  author: [NaT_Jerry , JL_NPE]
  commands:
    smg: # 命令的基本名，请不要使用奇怪的字符！
      aliases: # 别名，方便玩家使用
        - "smg"
        - "sendmessagetogroup"
      usage: "/smg [要发送的信息]" # 用法
      description: "发送信息给群里的人" # 描述
    botinvite:
      aliases:
        - "botinvite"
        - "inviteplayeringroup"
      usage: "/botinvite"
      description: "邀请服务器玩家"
    messageforwarding:
      aliases:
        - "mf"
        - "forwarding"
      usage: "/mf"
      description: "MessageForwarding"
    cwg:
      aliases:
        - "cwg"
        - "chatwithgroup"
      usage: "/cwg [reload/ver]"
      description: "重置CWG插件的配置文件或查看CWG版本"
    bind:
      aliases:
        - "bd"
        - "bangding"
      usage: "/bind [QQ ID]"
      description: "在游戏内绑定QQ号"
    broadcastmusic:
      aliases:
        - "bs"
        - "bm"
      usage: "/broadcastmusic <mp3URL>"
  permissions:
    cwg.*:
      description: All Permissions of CWG
      children:
        cwg.reload: true
        cwg.ver: true
        cwg.bind.force: true
        cwg.cache.purge: true
      default: op
    cwg.reload:
      description: The Player Who Has This Can Reload Config File
      default: op
    cwg.ver:
      description: The Player Who Has This Permission Can Look Up the Version info of CWG
      default: op
    cwg.bind.force:
      description: The Player Who Has This Permission Will Bind QQ and His UUID Without confirm
      default: op
    cwg.cache.purge:
      description: Purge Cache
      default: op